# Enumerate images and upload an index file.

name: Index Creator Workflow

on:
  push

permissions:
  contents: read

jobs:
  sync:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    steps:
      - name: Index creation
        shell: bash
        run: |
          rm .index-extended || true
          for d in "Named_Boxarts" "Named_Snaps" "Named_Titles" "Named_Logos" ;
          do
            if [[ -d $d ]] ; then
              cd $d
              for f in *.png ; do echo `date -r "$f" "+%Y-%m-%d"` `crc32 "$f"` $d/"$f" ; done >> ../.index-extended
              cd ..
            fi
          done
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated index file"
          git push
